sudo: required
language: bash
dist: trusty
services:
- docker
cache:
  directories:
  - ".terraform"
env:
  matrix:
  - TRAVIS_SECURE_ENV_VARS=true
  global:
    secure: kgOW1dHvpRVb9nSLgeDqr2C2QUWzwSi0c21krwo1yAtC5aBQ94r/Zm1xeVWOZgf/z0GEyMptfz4fAnpEehJ5J6yjPS2G9eirQuWsPzUd25z6xW12zODIkRu6nDjradngCIY3qcWRo4W83YjTAL2gnFzt2iX4p/ZhHUHkc08QGk7r56TnRUC4qN2i3WHnYVGAzrTZCEeNca1KsQmC6dLoqPpaUg71B2xcxZ0PI535BlBcBU+tZDznx6bhirkiFF1x0o1ZWsIbbHnNSDPUO3VCO77RzVFAPxQW91QBssYAMa7UVnMIJZne2sdpns62jJAsCfFDiftsOpoTf5X5EGvWcFvXVZ+esxqA/F/FwGHp59zeubU0Zqq6o3T6tR9fL1ZtcF+MMdgeVO/MdEpAs5iPGRhEqalUH8oSBrvX2BQNJ60A9T89QehhjN2kfZpNy6p6dEgNONjgcgZ6ovnwJmuLW+XXkYeixzsq/BxD0VEu0wk3l3ZgNNfuCGdZ/wBkRXQtkDr83wNp0pAy4k3LIYZg9ZXztZ/aWH2Q8m4+Sj96LzCZ9Nmkbt5WWNwAVjdqj2mtg6GzkSGHfRMG+6Y4ZBQD3bPFPq9rLA3S4aix4W5ORlutqA1AxlzDuY3w/juB3PPy9QI2EJji6LTouM2SeKKLs7ZrMzfckrgUyNGz7rpWGh0=
before_script:
- docker pull hashicorp/terraform:light
  - docker run -e "DO_API=${DO_API}"  -v $(pwd)/digital_ocean/centos:/x/ -w /x/ hashicorp/terraform:light init
  - docker run -e "DO_API=${DO_API}"  -v $(pwd)/digital_ocean/centos:/x/ -w /x/ hashicorp/terraform:light validate
  - docker run -e "DO_API=${DO_API}"  -v $(pwd)/digital_ocean/centos:/x/ -w /x/ hashicorp/terraform:light plan
  - docker run -e "DO_API=${DO_API}"  -v $(pwd)/digital_ocean/centos:/x/ -w /x/ hashicorp/terraform:light apply -auto-approve

notifications:
  email:
    on_success: never
    on_failure: always
